FROM registry.fedoraproject.org/fedora-toolbox:latest

WORKDIR /tmp/setup

# Install simple packages via DNF.
RUN dnf install -y \
        gcc \ 
        gcc-c++ \
        cmake \
        make \
        wayland-devel \
        alsa-lib-devel \
        libudev-devel \
        libxkbcommon \
        vulkan-tools && \
    dnf clean all

# Run special installation scripts.
COPY install-custom.sh .
RUN chmod +x install-custom.sh && ./install-custom.sh && dnf clean all
